name: CI

on: [push]

env:
  NODE_ENV: production
  PORT: 3000
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install
        env:
          NODE_ENV: development

      - name: Run typescript check
        run: yarn type-check

      - name: Run unit tests
        run: yarn jest

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          NODE_ENV: development
