name: CI

on: [push]

env:
  NODE_ENV: production
  PORT: 3000
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install
        env:
          NODE_ENV: development

      - name: Increase watchers limit
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Run typescript check and unit tests
        run: yarn jest

      - name: Cypress run
        uses: cypress-io/github-action@v2
