name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install --dev

      - name: Install danger code-coverage and jira-danger
        run: yarn add danger danger-plugin-istanbul-coverage danger-plugin-jira-issue --dev

      - name: Run all tests and collect coverage
        run: yarn test

      - name: Run eslint
        run: yarn eslint './**/*.{js,ts,tsx}' -f json -o eslint.json
        continue-on-error: true

      - name: Danger
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TNP_GITHUB_TOKEN }}
